data:
    image: busybox
    command: "true"
    volumes:
        - ./docs:/docs
        - ./public:/public

fetch:
    image: docsdockercom:${IMAGE_TAG}
    command: |
        /bin/bash -ec " \
        python fetch_content.py /docs all-projects.yml
        ./touch-up.sh /docs
        "
    volumes:
        - '.:/src'
    volumes_from:
        - data
    environment:
        - GITHUB_USERNAME
        - GITHUB_TOKEN

build:
    image: docsdockercom:${IMAGE_TAG}
    command: "hugo -d /public/$DOCS_VERSION"
    working_dir: /docs
    volumes_from:
        - data

upload:
    image: docsdockercom:${IMAGE_TAG}
    working_dir: /public
    command: /src/upload.sh
    volumes_from:
        - data
    environment:
        - CLEAN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_S3_BUCKET

cleanup:
    image: docsdockercom:${IMAGE_TAG}
    command: /src/cleanup.sh
    environment:
        - RM_OLDER_THAN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_S3_BUCKET

serve:
    image: docsdockercom:${IMAGE_TAG}
    working_dir: /docs
    command: "hugo server -d /public --port=8000 --baseUrl=$HUGO_BASE_URL --bind=0.0.0.0 --watch"
    ports:
        - "8000:8000"
    volumes_from:
        - data

test:
    image: docsdockercom:${IMAGE_TAG}
    working_dir: /docs
    command: 'python /src/docvalidate.py http://serve:8000'
    links:
        - serve
